replicaCount: 1

image:
  repository: ayushgharat234/task-service
  tag: latest
  pullPolicy: Always

imagePullSecrets: 
  - name: regcred 

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources: {}

env:
  REDIS_ADDR: "redis-master:6379"
  REDIS_PASS: ""

ingress:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}